version: '3'
services:
    nextcloud:
        container_name: nextcloud
        image: nextcloud
        restart: always
        ports:
            - 8088:80
        volumes:
            - nextcloud:/var/www/html/data
        depends_on:
            - mysql
    
    mysql:
        container_name: mysql
        image: 'mysql:8.0'
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: "nextcloud"
            MYSQL_USER: "root"
            MYSQL_ALLOW_EMPTY_PASSWORD: "true"
            MYSQL_ROOT_PASSWORD: ""
        volumes:
            - mysql:/var/lib/mysql


